name: clean_arch_bookly_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.0
  dartz: ^0.10.1
  dio: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  cached_network_image: ^3.3.1
  bloc: ^8.1.3
  shimmer: ^3.0.0
  widget_mask: ^1.0.0+0
  flutter_staggered_animations: ^1.1.1
  chips_choice: ^3.0.1
  svg_flutter: ^0.0.1
  nested: ^1.0.0
  loading_animation_widget: ^1.2.0+4
  country_picker: ^2.0.24
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.7
  top_snackbar_flutter: ^3.1.0
  validators: ^3.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.5
  fluttertoast: ^8.2.4
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.15.5
  awesome_dialog: ^3.2.0
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true
  assets:
    - assets/img/ 
    - assets/svg/ 
    - assets/img/logo/ 
    - assets/lang/ 
     
