name: clean_arch_bookly_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  dartz: ^0.10.1
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
  bloc: ^8.1.2
  meta: ^1.10.0
  shimmer: ^3.0.0
  widget_mask: ^1.0.0+0
  flutter_staggered_animations: ^1.1.1
  chips_choice: ^3.0.1
  svg_flutter: ^0.0.1
  nested: ^1.0.0
  loading_animation_widget: ^1.2.0+4
  country_picker: ^2.0.24
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true
  assets:
    - assets/img/ 
    - assets/svg/ 
    - assets/img/logo/ 
     
